### ISSUE TITLE
如何检查pccs服务是否开启了tls?

### ISSUE THREAD

**Issue by joaquinboss** [secretflow/capsule-manager#18]
系统是ubuntu20.04，已经配置好SGX环境了，目前跟着trustedflow文档的SGX模式
貌似已经配置好PCCS了，输入sudo systemctl status pccs，输出如下图
![2024-05-28 11-21-19屏幕截图](https://github.com/secretflow/capsule-manager/assets/74462597/1019f6a0-e056-49e5-ae0f-3aa44d3fd7a9)
请问大佬们，如何检查PCCS服务是否开启tls?
因为需要用在实际生产中，需要开启tls

**Comment by zhongtianq** [comment]
可以在访问pccs配置/etc/sgx_default_qcnl.conf 中设置"use_secure_cert": true 。如果能成功访问就是开启了tls
