### ISSUE TITLE
数据密钥加解密问题

### ISSUE THREAD

**Issue by walkovernamtso** [secretflow/capsule-manager#31]
数据密钥的加密密钥在sdk用的临时密钥，在capsulemanager端解密用的私钥，这怎么回事呢，求专家答疑

sdk端加密代码：
        # generate temp data_key, it will be used to encrypt data
        data_key = AESGCM.generate_key(bit_length=128)
        # use public key of capsule manager to encrypt data key
        jwe.encrypted_key = tool.encode_base64(
            asymm.RsaEncryptor(public_key, "RSA-OAEP-256").encrypt(data_key)
        )

        nonce = crypto.gen_key(NONCE_SIZE_IN_SIZE)
        jwe.iv = tool.encode_base64(nonce)
        jwe.aad = ""

        (ciphertext, tag) = symm.AesGcmEncryptor(data_key, "A128GCM").encrypt(
            json_format.MessageToJson(jws).encode("utf-8"), nonce, b""
        )

capsulemanager端解密代码：
    let content = encrypt_request
        .message
        .as_ref()
        .ok_or(errno!(ErrorCode::NotFound, "Request content"))?;

    let jwe: jwe::Jwe = from(&content)?;
    log::debug!(target: "capsule_manager_log", "{:?}", &jwe);
    let secret = Secret::keypair_from_pem(private_key_pem)?;
    let plain_text = jwe.decrypt(&secret)?;

**Comment by BrainWH** [comment]
数据密钥用capsule manager的公钥加密上传，capsule manager用私钥解密。随机生成的是data key，加密data key用的就是capsule manager的公钥

**Comment by walkovernamtso** [comment]
此data_key非数据密钥，是临时密钥，真正的数据密钥在jws里面。所以这个逻辑感觉比较迷惑

**Comment by BrainWH** [comment]
jwe里面的临时密钥随机生成，临时密钥加密报文，之后capsule manager的公钥加密了临时密钥。可以参照trustflow原理https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/architecture/principle

**Comment by walkovernamtso** [comment]
> jwe里面的临时密钥随机生成，临时密钥加密报文，之后capsule manager的公钥加密了临时密钥。可以参照trustflow原理https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/architecture/principle

是这样，这块没疑问。我的问题是解密为什么用私钥可以直接解密，按道理应该是私钥把临时密钥解出来，然后再用临时密钥把数据密钥解出来

**Comment by walkovernamtso** [comment]
学习完JWE，问题解决了，谢谢解答
