### ISSUE TITLE
SGX驱动安装失败

### ISSUE THREAD

**Issue by rrsakura** [secretflow/capsule-manager#32]
SGX驱动安装失败，cpu是支持SGX的，按照https://www.alibabacloud.com/help/zh/ecs/user-guide/build-an-sgx-encrypted-computing-environment#53b0d34b7cnlu 安装SGX驱动的时候显示安装失败，以下是报错信息：

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2700 kB]
Fetched 3084 kB in 4s (837 kB/s)    
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
curl is already the newest version (7.81.0-1ubuntu1.18).
dkms is already the newest version (2.8.7-2ubuntu2.2).
wget is already the newest version (1.21.2-2ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40492  100 40492    0     0  52574      0 --:--:-- --:--:-- --:--:-- 52518
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-P8ACcw /home/admin/dev/SGX-hardware
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
cp -r package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
/home/admin/dev/SGX-hardware
Creating symlink /var/lib/dkms/sgx/1.41/source -> /usr/src/sgx-1.41

Failed to build driver.

请问不在UEFI模式下可以安装该驱动吗？

**Comment by BrainWH** [comment]
可以提个阿里云的工单
