### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by PrimumMobile** [secretflow/capsule-manager#5]
参照trustedflow部署遇到如下问题：
![image](https://github.com/secretflow/capsule-manager/assets/120082883/2ae4fec0-79ea-4fb3-94b3-39446c35a343)

并没有开启tls，在teeapps执行
./main --plat=sim --enable_console_logger=true --enable_capsule_tls=false --entry_task_config_path=/host/integration_test/psi_task.json时候出现的

**Comment by zheyang0825** [comment]
capsule-manager 有日志吗输出吗？可以进到 capsule manager 的容器里，看一下 logs 目录下的日志吗？

**Comment by zheyang0825** [comment]
> <img alt="1711691127496" width="578" src="https://private-user-images.githubusercontent.com/120082883/317964477-ee7373be-7948-4cae-b58b-8e71658d7f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTE2NzAsIm5iZiI6MTcxMTY5MTM3MCwicGF0aCI6Ii8xMjAwODI4ODMvMzE3OTY0NDc3LWVlNzM3M2JlLTc5NDgtNGNhZS1iNThiLThlNzE2NThkN2Y3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwNTQ5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTkzMmU3Y2M2MTM3ODc5ZTM1ZTM2ZWY1MTdjYzdlZDFhMmNiM2ZjNTcyNjJjODk1MjMyN2ZhZjg3Yjc2MmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRp-Vtf2wxfmM9bTjqO3xI4pXkKqCRY1SG5ctTEVdAo">
> 日志有输出，bob提交策略是正常的

但是 teeapps 请求没有，大概率是 teeapps 配置的地址不对
