### ISSUE TITLE
关于trustedflow TEE方面的问题，请帮忙解答

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager#9]
1、        当前数据血缘能力未实现，在获取加密结果审批中所有数据提供方包括数据血缘追溯到的最终父提供方吗？
2、        密态spark能力在哪里体现？
3、        可信app如何保证可信？
4、        海光CSV环境下，trustedflow是以虚机还是docker形式支持？
5、        可信app对数据存在在哪里？如何存储？如何保证安全
6、       数据集是否支持数据库形式提供？

**Comment by zhouaihui** [comment]
hi, @qinjuana ,
感谢您的提问。问题比较多，可以每个问题单独一个issue吗，这样方便更聚焦的沟通。

**Comment by zhongtianq** [comment]
已经拆分成多个issue单独回答，此issue close
